name: Verificación y compilación de dossier
on: push
jobs:
  validate-and-render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: typst-community/setup-typst@v4
        with:
          cache-dependency-path: requirements.typ
      
      - name: Correr Stress Tests
        run: make test

      - name: Generar Documentos PDF
        run: |
          make pdf-cpp
          make pdf-python

      # Subir los archivos generados si todo ha salido bien
      - name: Subir archivos generados
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout ${{ github.ref_name }}
          git add python.pdf cpp.pdf
          # Solo hacer commit si hay cambios reales para evitar bucles
          git diff-index --quiet HEAD || git commit -m "chore: Actualizar PDFs (Auto-generado por CI)"
          git push origin ${{ github.ref_name }}
